### ISSUE TITLE
Issues running `goapp deploy` in Section 4

### ISSUE THREAD

**Issue by gmarik** [campoy/go-web-workshop#22]
Had issues following the tutorial [at the deployment step](https://github.com/campoy/go-web-workshop/tree/master/section04#deploy-to-the-app-engine-servers)
```
$ goapp deploy --version=1 --application=appname-123456 .
...
... auth process here...
....
Authentication successful.
02:19 AM Scanning files on local disk.
Error 404: --- begin server output ---
This application does not exist (project_id=u'appname-123456'). To create an App Engine application in this project, run "gcloud beta app create" in your console.
--- end server output ---
error while running appcfg.py: exit status 1
```

The solution was to download `gcloud` cli and do a dance with.

Here's the blog post of [my appengine experience](https://www.gmarik.info/blog/2017/appengine-experience/)

**Comment by campoy** [comment]
Are you authenticated with the right account?
I see this error when I have more than one account and I use the wrong one.

**Comment by campoy** [comment]
I migrated the workshop to use `gcloud` now, give it a try again
